### ISSUE TITLE
Black screen in raids

### ISSUE THREAD

**Issue by jamesdileva** [Runemoro/better-renderer#13] opened 2020-11-15 05:00 UTC
![image](https://user-images.githubusercontent.com/23731579/99169925-02f12f80-26bc-11eb-89e0-1ee1d53acded.png)
Hello this was inside the raid. Outside the render was off as well I tried with zoom off and on but it was hard to click on the entrance for example

**Comment by Runemoro** [comment] 2020-11-15 14:43
Duplicate of #6. Currently instances aren't working properly but I'll be start working on a fix as soon as possible.

**Closed by Runemoro** 2020-11-15 14:43 UTC
